name = "OpenHPLJulia"
uuid = "cf8b2112-c722-4ef9-8a49-1633b996a987"
authors = ["pandeysudan27 <pandeysudan27@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
